### ISSUE TITLE
Image translation

### ISSUE THREAD

**Issue by greenroach** [translation-gang/vue-cli#1]
Browser Браузер
UI Client
Loads
Client addon
Component
Routes
GraphQL
SharedData
Plugin Action
Ui Server
Plugin
Plugin API
User project
Config
Task(script)
Describes
Webpack plugin
IPC
Child Process
Through Plugin API
Your vue-cli plugin

![vue-cli-ui-schema](https://user-images.githubusercontent.com/6224866/42886897-6839c27e-8aad-11e8-889e-60c4d7547f9c.png)

**Comment by Alex-Sokolov** [comment]
Browser — Браузер
UI Client — Пользовательский UI
Loads — Загружает
Client Addon — Клиентское дополнение
Component — Компонент
Routes — Маршруты
Shared Data — Общие данные
Plugin Action — Действия плагина
UI Server — Сервер UI
Plugin — Плагин
Plugin API — API плагина
Uses & modifies — Использует и изменяет
Describes — Описывает
User project — Проект пользователя
Config — Конфигурация
Task (script) — Задачи (скрипты)
Webpack plugin — плагин Webpack
Child process — Дочерний процесс
Through Plugin API — через API плагина
You vue-cli plugin — Ваш плагин для vue-cli

**Comment by Alex-Sokolov** [comment]
ping @greenroach
